# This is a basic workflow that is manually triggered

name: Update example
on:
  push:
    branches: [ master ]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
    - run: sudo apt install scrot
    - run: chmod +x "${GITHUB_WORKSPACE}/create_example.sh"    
    - name: Build
      run: cargo build --debug
    - name: Update example
      run: "${GITHUB_WORKSPACE}/create_example.sh"
      working-directory: .
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'img/example.png'
        message: 'update example'
